# Generated by Django 3.2.8 on 2021-11-21 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extensionidentifierstr',
            name='trackSite',
        ),
    ]
