# Generated by Django 3.2.7 on 2021-10-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='dateAdded',
            field=models.DateTimeField(verbose_name='Date added'),
        ),
    ]
