# Generated by Django 3.2.8 on 2021-10-30 08:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='last_ping',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last pinged'),
            preserve_default=False,
        ),
    ]
